TNG/ArchUnitNET

ArchUnitNET/Fluent/Syntax/Elements/ObjectConditionsDefinition.cs, ArchUnitNETTests/Fluent/DependencyErrorMessageTests.cs
When failing the "NotDependOnAny" Rule the error message now only shows the forbidden dependencies
=> Improve Error Messages

ArchUnitNET/Fluent/ConditionManager.cs, ArchUnitNETTests/Fluent/MultipleConditionRulesTests.cs
This fixes a bug where the error message of an ArchRule with multiple conditions sometimes displayed incorrect types as failed.
=> Bugfix wrong error message of rules with multiple conditions

Travis/test_windows.ps1
If dotnet build fails, the whole travis build will fail now
Test ArchUnitNET in Debug mode, because otherwise some tests are skipped
=> Update Travis Build/Test Skript

ArchUnitNET/Loader/MonoCecilTypeExtensions.cs, ArchUnitNETTests/GithubIssuesTests/GithubIssue46Test.cs
Include all Generic Parameters of the Declaring Type/Method in the full name of a Generic Parameter to ensure that the full name is unique for every Generic Parameter.
This fixes Issue #46
=> Issue #46 Fix

ArchUnitNET/Domain/Dependencies/ImplementsInterfaceDependency.cs, ArchUnitNET/Loader/LoadTasks/AddClassDependencies.cs, ArchUnitNET/Loader/TypeFactory.cs
resolved issue where building the architecture could fail if interfaces from unresolvable assemblies where implemented
=> fix Issues #51 and #61

ArchUnit.sln, ArchUnitNET.MSTestV2/ArchRuleAssert.cs, ArchUnitNET.MSTestV2/ArchRuleExtensions.cs, ArchUnitNET.MSTestV2/ArchUnitNET.MSTestV2.csproj, ArchUnitNET.MSTestV2Tests/ArchUnitNET.MSTestV2Tests.csproj, ArchUnitNET.MSTestV2Tests/RuleEvaluationTests.cs, README.md, Travis/deploy.ps1
A new package referencing MSTestV2 is created for adding the same shortcuts as in ArchUnitNET.NUnit.
This would reduce the usage of ArchUnitNET with MSTestV2 including meaningful messages from:
```csharp
[TestMethod]
public void ExampleCycleCheck()
{
IArchRule rule = Slices().Matching("..").Should().BeFreeOfCycles();
if (!archRule.HasNoViolations(_architecture))
{
Assert.Fail(archRule.Evaluate(architecture).ToErrorMessage());
}
}
```
To:
```csharp
[TestMethod]
public void ExampleCycleCheck()
{
IArchRule rule = Slices().Matching("..").Should().BeFreeOfCycles();
rule.Check(_architecture);
}
```
Please create and upload the according Nuget packages.
=> Add extensions for MSTest V2 framework.

ArchUnitNET/Loader/TypeFactory.cs, ArchUnitNETTests/ArchUnitNETTests.csproj, ArchUnitNETTests/Domain/FixedSizeBufferTests.cs
This fixes an issue, where fixed size buffers (eg. `unsafe fixed char buffer[256]`) were not assigned the correct field type (eg. `char[]`) but instead had a compiler generated field type.
=> Handle fixed size buffers

ArchUnitNET/Domain/FieldMember.cs, ArchUnitNET/Domain/IMember.cs, ArchUnitNET/Domain/MethodMember.cs, ArchUnitNET/Domain/PropertyMember.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/GivenMembersThat.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/IMemberConditions.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/IMemberPredicates.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/MemberConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/MemberPredicatesDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/MembersShould.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/ShouldRelateToMembersThat.cs, ArchUnitNET/Loader/LoadTasks/AddMembers.cs, ArchUnitNET/Loader/TypeFactory.cs, ArchUnitNETTests/Fluent/Extensions/BuildMocksExtensions.cs, ArchUnitNETTests/Fluent/Syntax/Elements/MemberSyntaxElementsTests.cs
expose the IsStatic property from Mono Cecils MethodDefinition and FieldDefinition as requested in #97
=> Expose IsStatic property on members

ArchUnitNET/Fluent/Syntax/Elements/GivenObjectsThat.cs, ArchUnitNET/Fluent/Syntax/Elements/IObjectConditions.cs, ArchUnitNET/Fluent/Syntax/Elements/IObjectPredicates.cs, ArchUnitNET/Fluent/Syntax/Elements/ObjectConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/ObjectPredicatesDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/ObjectsShould.cs, ArchUnitNET/Fluent/Syntax/Elements/ShouldRelateToObjectsThat.cs
Only extended the public interface a bit by adding an optional parameter `useRegularExpressions` to allow regex matching instead of only `contains`.
Internals of the library remain unchanged.
Signed-off-by: Thomas De Craemer <1496708+thomasdc@users.noreply.github.com>
=> Allow regex matching on name and full name when providing a string pattern

ArchUnitNET/Fluent/Syntax/Elements/ObjectConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/ObjectPredicatesDefinition.cs, ArchUnitNET/Loader/MonoCecilAttributeExtensions.cs, ArchUnitNETTests/Domain/AttributeArgumentTests.cs
Fix a bug where Attributes with null as argument could lead to an ArgumentNullException during build of the architecture.
This implements and fixes the testcase from PR #110
=> Fix attribute argument bug

ArchUnitNET/Domain/IHasDescription.cs, ArchUnitNET/Domain/IObjectProvider.cs, ArchUnitNET/Domain/MethodMemberInstance.cs, ArchUnitNET/Fluent/Extensions/SyntaxElementExtensions.cs, ArchUnitNET/Fluent/LogicalConjunction.cs, ArchUnitNET/Fluent/Slices/SliceIdentifier.cs, ArchUnitNETTests/ArchitectureTests/ArchUnitArchitectureTests.cs
this removes the circular dependencies pointed out in the first test of #112
=> refractor circular dependencies between Domain, Fluent and Loader

ArchUnitNET/Domain/Extensions/NamingExtensions.cs, ArchUnitNET/Domain/Extensions/TypeExtensions.cs, ArchUnitNET/Fluent/Syntax/Elements/GivenObjectsThat.cs, ArchUnitNET/Fluent/Syntax/Elements/IObjectConditions.cs, ArchUnitNET/Fluent/Syntax/Elements/IObjectPredicates.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/MemberConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/MemberPredicatesDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/MethodMembers/MethodMemberConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Members/MethodMembers/MethodMemberPredicatesDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/ObjectConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/ObjectPredicatesDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/ObjectsShould.cs, ArchUnitNET/Fluent/Syntax/Elements/ShouldRelateToObjectsThat.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/TypeConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/TypePredicatesDefinition.cs, ArchUnitNETTests/Dependencies/ExternalDependenciesTests.cs, ArchUnitNETTests/Domain/Extensions/TypeExtensionTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/MatchGenericReturnTypesTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/MemberSyntaxElementsTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/MethodMemberSyntaxElementsTests.cs
If regex use is not explicitly specified, patterns now only match the name and full name of types, if they are exactly equal. Previously it also matched if the name contained the pattern. One problem with this was for example that the name of a parent namespaces matched to all child namespaces.
=> Change matching of name and fullname patterns to exact match by default

ArchUnitNET/Fluent/Syntax/Elements/ObjectConditionsDefinition.cs, ArchUnitNETTests/Fluent/ObjectConditionsErrorMessagesTests.cs, TestAssembly/ClassCallingOtherMethod.cs
There was a bug in the error reports when types depend on forbidden types or methods are calling forbidden methods. Due to a Union being used instead of an Intersect, all dependencies were reported in the error instead of only the ones that are forbidden. This should fix #143
=> Only list forbidden dependencies in error messages

ArchUnitNET/Domain/Class.cs, ArchUnitNET/Domain/Enum.cs, ArchUnitNET/Domain/Extensions/TypeExtensions.cs, ArchUnitNET/Domain/GenericParameter.cs, ArchUnitNET/Domain/IType.cs, ArchUnitNET/Domain/Interface.cs, ArchUnitNET/Domain/Struct.cs, ArchUnitNET/Loader/Type.cs, ArchUnitNETTests/Domain/InterfaceTests.cs, ArchUnitNETTests/Loader/TypeTests.cs
The behaviour doesn't change except for Type, which should not be used for analysis
=> Rewrite IsAssignableTo() and ImplementsInterface() methods as TypeExtensions

ArchUnitNET/Fluent/Syntax/Elements/Types/GivenTypesThat.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/ITypeConditions.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/ITypePredicates.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/ShouldRelateToTypesThat.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/TypeConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/TypePredicatesDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/TypesShould.cs, ArchUnitNETTests/Fluent/Syntax/Elements/TypeSyntaxElementsTests.cs
enhances ResideInAssembly() as requested in #131
=> Allow Domain.Assembly as input parameter for ResideInAssembly()

ArchUnitNET/Loader/ArchLoader.cs, ArchUnitNET/Loader/FilterResult.cs, ArchUnitNETTests/Loader/ArchLoaderTests.cs
Should resolve https://github.com/TNG/ArchUnitNET/issues/164
Added new overload with custom filter delegate. This delegate is passed through LoadModule to AddReferencedAssembliesRecursively. I've decided to reuse existing private methods, and add delegate as new argument with default value = null. When the delegate is null methods behavior should remain exactly as it was before.
=> Added LoadAssembliesRecursively with custom load filter function support

ArchUnitNET.MSTestV2Tests/RuleEvaluationTests.cs, ArchUnitNET.NUnitTests/RuleEvaluationTests.cs, ArchUnitNETTests/Dependencies/ExternalDependenciesTests.cs, ArchUnitNETTests/Domain/Dependencies/Members/GetterSetterTestsBuild.cs, ArchUnitNETTests/Fluent/MultipleConditionRulesTests.cs, ArchUnitNETTests/Fluent/NoErrorReferencingOfTypesOutsideOfArchitectureTests.cs, ArchUnitNETTests/Fluent/Syntax/DependenciesToOtherAssembliesTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/CustomSyntaxElementsTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/MatchGenericReturnTypesTests.cs, ArchUnitNETTests/Loader/NestedTypesTests.cs, ExampleTest/ExampleArchUnitTest.cs, README.md, documentation/docs/guide.md
Related to: `Question: Load assemblies example` #177 
this will make the test more robust in case you move classes to other assembly which could break your architecture without detecting with the tests.
=> chore change example and test how to load assemblies 

.travis.yml, global.json
Signed-off-by: Andrii Derevianko <andredered@gmail.com>
NET SDK to v6.0.402 in travis.yml and global.json update
=> Update dependency dotnet-sdk to v6

ArchUnitNET/Domain/Extensions/AssemblyExtensions.cs, ArchUnitNET/Fluent/CustomArchRule.cs, ArchUnitNET/Library/Rules/TargetFrameworkRules.cs
Start a library of example rules with 3 examples for checking the target framework of a project.
Inspired by https://gaevoy.com/2022/05/19/review-dependencies-on-every-commit.html
=> Add example rules for testing the target framework of an Architecture

README.md
Add a missing closing parenthesis missing in the readme code example
=> Add missing closing parenthesis in readme

ArchUnitNET/Fluent/ArchRule.cs, ArchUnitNET/Fluent/ArchRuleCreator.cs, ArchUnitNET/Fluent/CombinedArchRuleCreator.cs, ArchUnitNET/Fluent/ConditionManager.cs, ArchUnitNET/Fluent/IArchRuleCreator.cs, ArchUnitNET/Fluent/Syntax/Elements/ObjectsShould.cs, ArchUnitNETTests/Fluent/RuleEvaluationTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/MemberSyntaxElementsTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/MethodMemberSyntaxElementsTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/ObjectSyntaxElementsTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/PropertyMemberSyntaxElementsTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/TypeSyntaxElementsTests.cs, ExampleTest/ExampleArchUnitTest.cs
This is a breaking change that requires rules to yield positive results by default. The intent is to protect against misformulated rules.
This is the first public iteration. It still loses type information on WithoutRequiringPositiveResults(), but otherwise I think it's fine.
Resolves #189
=> Require positive results by default

ArchUnitNET/Loader/ArchBuilder.cs, ArchUnitNET/Loader/MonoCecilMemberExtensions.cs
- In `ArchUnitNET/Loader/ArchBuilder.cs` we use a `Dictionary` instead of a `List` for a more efficient lookup. In my tests this improves loding times for lange numbers of assembiles and halfes the execution time for the `LoadAssembliesIncludingRecursiveDependencies` test.
- Small performance improvement in `ArchUnitNET/Loader/MonoCecilMemberExtensions.cs` by performing checks more efficiently.
=> perf(loader): improve assembly loading

ArchUnitNET/Domain/Class.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/Classes/ClassConditionsDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/Classes/ClassPredicatesDefinition.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/Classes/ClassesShould.cs, ArchUnitNET/Fluent/Syntax/Elements/Types/Classes/GivenClassesThat.cs, ArchUnitNET/Loader/MonoCecilTypeExtensions.cs, ArchUnitNET/Loader/TypeFactory.cs, ArchUnitNETTests/Fluent/Syntax/Elements/ClassSyntaxElementsTests.cs
Identifies if a class is a record if it has a methode named "<Clone>$"
inspired from this post: [stackoverflow](https://stackoverflow.com/questions/64809750/how-to-check-if-type-is-a-record)
=> added Fluent Syntax for classes that are records

ArchUnitNET/Domain/ArchitectureCache.cs, ArchUnitNETTests/Domain/ArchitectureCacheTests.cs, ArchUnitNETTests/Domain/TestArchitectureCache.cs
This is a least effort implementation of a clearable Architecture cache. This will allow calls to `ArchitectureCache.Instance.Clear()` from external sources in scenarios where a uniqueness of the `ArchitectureCacheKey` during the runtime of the consuming app cannot be guaranteed and thus, the `Cache` needs to be cleared between executions of the `ArchBuilder` resp. `ArchLoader´.
=> Issue: #269 Least effort implementation of a clearable Architecture cache

ArchUnit.sln, ArchUnitNET/Loader/ArchBuilder.cs, ArchUnitNET/Loader/TypeFactory.cs, ArchUnitNET/Loader/TypeRegistry.cs, ArchUnitNETTests/ArchUnitNETTests.csproj, ArchUnitNETTests/Loader/ArchLoaderTests.cs, ArchUnitNETTests/StaticTestArchitectures.cs, TestAssemblies/LoaderTestAssembly/DuplicateClassAcrossAssemblies.cs, TestAssemblies/LoaderTestAssembly/LoaderTestAssembly.cs, TestAssemblies/LoaderTestAssembly/LoaderTestAssembly.csproj, TestAssemblies/OtherLoaderTestAssembly/DuplicateClassAcrossAssemblies.cs, TestAssemblies/OtherLoaderTestAssembly/OtherLoaderTestAssembly.cs, TestAssemblies/OtherLoaderTestAssembly/OtherLoaderTestAssembly.csproj
Fixes #292, adding the ability to `ArchBuilder` and `TypeRegistry` to differentiate between types with the same full name but from different assemblies.
=> Loader: Match Types By Assembly Qualified Name

ArchUnitNET/Loader/LoadTasks/AddAttributesAndAttributeDependencies.cs, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.DependOnAnyTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.OnlyDependOnTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.OnlyDependOnTypesThatTest.verified.txt
Relates to #229. Compiler Attributes are currently filtered in the [`ArchBuilder`]( https://github.com/TNG/ArchUnitNET/blob/1bfa1e624924a8a76ffceaf17576c3cbd0c2a1c7/ArchUnitNET/Loader/ArchBuilder.cs#L82) but are still introduced to the architecture through the `AddAttributesAndAttributeDependencies` load task.
With this patch, the attributes `Microsoft.CodeAnalysis.EmbeddedAttribute`, `System.Runtime.CompilerServices.NullableAttribute` and `System.Runtime.CompilerServices.NullableContextAttribute` will also be filtered in that load task.
=> Completely Filter Compiler Attributes from Architecture

ArchUnitNET.NUnitTests/ArchUnitNET.NUnitTests.csproj, ArchUnitNET.xUnit/ArchUnitNET.xUnit.csproj
`System.Net.Http` 4.3.0 and `System.Text.RegularExpressions` 4.3.0 have know security vulnerabilities. We update `NUnit3TestAdapter` in `ArchUnitNET.NUnitTests.csproj` and pin `System.Net.Http` and `System.Text.RegularExpressions` to fixed versions in `ArchUnitNET.xUnit.csproj` to resolve these warnings.
=> Resolve Security Vulnerability Warnings

ArchUnit.sln, ArchUnitNET/Domain/UnavailableType.cs, ArchUnitNET/Loader/TypeFactory.cs, ArchUnitNETTests/ArchUnitNETTests.csproj, ArchUnitNETTests/Loader/ArchLoaderTests.cs, TestAssemblies/AttributeAssembly/AttributeAssembly.csproj, TestAssemblies/DependencyAssembly/DependencyAssembly.csproj, TestAssemblies/FilteredDirectoryLoaderTestAssembly/Class1.cs, TestAssemblies/FilteredDirectoryLoaderTestAssembly/FilteredDirectoryLoaderTestAssembly.csproj, TestAssemblies/FilteredDirectoryLoaderTestAssembly/FilteredDirectoryLoaderTestAssembly.sln, TestAssemblies/LoaderTestAssembly/LoaderTestAssembly.csproj, TestAssemblies/OtherLoaderTestAssembly/OtherLoaderTestAssembly.csproj, TestAssemblies/VisibilityAssembly/VisibilityAssembly.csproj
When assemblies are loaded by path, there are cases where a dependent type cannot be resolved because the assembly dependency is not loaded in the current application domain. In this case, we create a stub type.
Fixes #325
=> fix: dont throw exception if a type can not be resolved

ExampleTest/LimitationsOnReleaseTest.cs, README.md, documentation/docs/limitations/debug_artifacts.md
=> Add Documentation for Async Function Limitations in Release Builds

.github/workflows/label-issues.yaml
New issues should automatically be labelled with `needs-triage`
=> Add Workflow to Automatically Label New Issues

ArchUnitNET/Domain/GenericParameter.cs, ArchUnitNET/Loader/LoadTasks/AddGenericParameterDependencies.cs, ArchUnitNET/Loader/TypeFactory.cs, TestAssemblies/DependencyAssembly/TypeDependency.cs
Revert change from #318 that can load on an exception for nested functions with generic parameters and add a class that correctly covers this case.
=> Break Recursion in Resolving Generic Arguments of Nested Functions

ArchUnitNETTests/AssemblyTestHelper/AttributeAssemblyTestHelper.cs, ArchUnitNETTests/AssemblyTestHelper/DependencyAssemblyTestHelpers.cs, ArchUnitNETTests/AssemblyTestHelper/VisibilityAssemblyTestHelper.cs, ArchUnitNETTests/Fluent/Syntax/Elements/ObjectsShouldTests.cs, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.HaveAnyAttributesTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.HaveAnyAttributesThatTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.HaveAnyAttributesWithArgumentsTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.HaveAnyAttributesWithNamedArguments.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.HaveAttributeWithArgumentsTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.HaveAttributeWithNamedArguments.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.NotHaveAnyAttributesTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.NotHaveAnyAttributesWithArgumentsTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.NotHaveAnyAttributesWithNamedArgumentsTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.NotHaveAttributeWithArgumentsTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.NotHaveAttributeWithNamedArgumentsTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.NotHaveNameTest.verified.txt, ArchUnitNETTests/Fluent/Syntax/Elements/Snapshots/ObjectsShouldTests.OnlyHaveAttributesTest.verified.txt, TestAssemblies/AttributeAssembly/AttributeAssembly.cs
Refactoring of the Attribute Assemlby to be better suited for the upcoming predicate tests.
=> Refactor AttributeAssembly

ArchUnit.sln, ArchUnitNET/Loader/MonoCecilAttributeExtensions.cs, ArchUnitNETTests/Loader/ArchLoaderTests.cs, FilteredDirectoryAssemblyAttributeAssembly/AssemblyAttribute.cs, FilteredDirectoryAssemblyAttributeAssembly/FilteredDirectoryAssemblyAttributeAssembly.csproj, TestAssemblies/FilteredDirectoryLoaderTestAssembly/Class1.cs, TestAssemblies/FilteredDirectoryLoaderTestAssembly/FilteredDirectoryLoaderTestAssembly.csproj
As a fix for #398, we wrap UnavailableType instances in Attribute instances when creating an Attribute of a type whose Assembly is not available.
=> Handle UnavailableType when creating an Attribute

renovate.json
We do not want to force newer versions for xunit.v3 and TUnit for the released ArchUnitNET packages
=> Exclude xunit.v3 and TUnit from Updates for released packages

ArchUnitNETTests/ArchUnitNETTests.csproj, ArchUnitNETTests/Dependencies/CppDependenciesTests.cs
C++/CLI is only supported on Windows. We therefore change the tests regarding C++/CLI to only run on Windows.
=> Run C++/CLI Test only on Windows
