ArchUnitNET/Core/LoadTasks/AddMethodDependencies.cs
ArchUnitNET/Fluent/Extensions/MonoCecilMemberExtensions.cs

fixed wrong assignment of MethodCallDependencies to generic static methods

---

ArchUnitNET/Core/LoadTasks/AddMembers.cs
ArchUnitNET/Core/LoadTasks/AddMethodDependencies.cs
ArchUnitNET/Domain/GenericParameter.cs
ArchUnitNET/Domain/MethodMember.cs
ArchUnitNET/Fluent/Extensions/MonoCecilMemberExtensions.cs
ArchUnitNET/Fluent/Extensions/TypeExtensions.cs
ArchUnitNETTests/Fluent/Extensions/BuildMocksExtensions.cs

fixed another occurrence where MethodCallDependencies to generic static methods where not assigned correctly

---

ArchUnitNET/Domain/Attribute.cs

Signed-off-by: GeorgKreuzmayr <g.kreuzmayr@gmail.com>

Fix typo in attribute constructor

---

.travis.yml
Travis/deploy.ps1

Fixing the relative path in windows deploy script
Signed-off-by: GeorgKreuzmayr <g.kreuzmayr@gmail.com>

Fix relative path, remove tag

---

ArchUnitNET.NUnit/ArchUnitNET.NUnit.csproj
ArchUnitNET.xUnit/ArchUnitNET.xUnit.csproj
ArchUnitNET/ArchUnitNET.csproj

Downgrade target .net framework from 4.8 to 4.5 to be compatible with more projects
Resolve issue #13

Framework downgrade

---

ArchUnitNET/ArchUnitNET.csproj
ArchUnitNET/Domain/Class.cs
ArchUnitNET/Domain/Extensions/TypeExtensions.cs
ArchUnitNET/Domain/PropertyMember.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MemberPredicatesDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Types/TypePredicatesDefinition.cs

This fixes code, which was incompatible with .NET Framework 4.5

Framework 4.5 compatibility fix

---

ExampleTest/LimitationsOnReleaseTest.cs
Travis/test_linux.sh
documentation/docs/api.md
documentation/docs/limitations/debug_artifacts.md

Added documentation of edge cases for readthedocs where testing in Debug mode can lead to other results than testing in Release mode.

Debug vs Release testing

---

ArchUnitNET.xUnit/ArchRuleAssert.cs
ArchUnitNET.xUnit/ArchRuleAsserts.cs
ArchUnitNET.xUnit/ArchRuleExtensions.cs
ArchUnitNET.xUnit/ArchUnitNET.xUnit.csproj
ArchUnitNET.xUnit/FailedArchRuleException.cs
ArchUnitNETTests/ArchUnitNETTests.csproj
ArchUnitNETTests/ArchitectureTests/ArchUnitArchitectureTests.cs
ArchUnitNETTests/Fluent/RuleEvaluationTests.cs
ArchUnitNETTests/Fluent/Slices/SlicesTests.cs
ArchUnitNETTests/Fluent/Syntax/Elements/CustomSyntaxElementsTests.cs
ArchUnitNETTests/Fluent/Syntax/Elements/ObjectSyntaxElementsTests.cs
ArchUnitNETTests/StaticTestArchitectures.cs
ExampleTest/ExampleArchUnitTest.cs
ExampleTest/ExampleTest.csproj

rename xUnit Assert to ArchRuleAssert and move it to ArchUnitNET.xUnit namespace

Xunit assert fix

---

documentation/Doxyfile

Fix gh-pages Link to point to doxygen created index.html file

Update Doxyfile to generate html files in current directory

---

Travis/deploy_documentation.sh
Travis/generate_documentation.sh

Fix check if index.html file was created

Fix documentation deployment script

---

ArchUnitNET/Domain/Attribute.cs
ArchUnitNET/Loader/LoadTasks/AddAttributesAndAttributeDependencies.cs

fix that dependencies to attributes from unresolvable assemblies resulted in a build error while building the architecture (#51)

---

ArchUnitNET/Domain/PlantUml/ClassDiagramAssociation.cs
todo.txt

Signed-off-by: Marco Studer <marco.studer@bison-group.com>

fix component name order in case of ComponentIntersectionException

---

ArchUnitNET/Domain/Assembly.cs
ArchUnitNET/Loader/ArchBuilder.cs
ArchUnitNET/Loader/AssemblyRegistry.cs
ArchUnitNET/Loader/LoadTasks/AddAttributesAndAttributeDependencies.cs
ArchUnitNET/Loader/LoadTasks/CollectAssemblyAttributes.cs
ArchUnitNET/Loader/MonoCecilAttributeExtensions.cs
ArchUnitNETTests/Loader/AssemblyAttributesTests.cs
TestAssembly/AssemblyTestAttribute.cs
TestAssembly/TestAssembly.csproj

Collect attributes from assemblies as requested in #98

Feature assembly attributes

---

documentation/docs/guide.md

Signed-off-by: Marco Studer <marco.studer@bison-group.com>

#95 Add PlantUml documentation to User Guide

---

ArchUnitNET/Loader/LoadTasks/AddMethodDependencies.cs
ArchUnitNET/Loader/MonoCecilMemberExtensions.cs
ArchUnitNETTests/Domain/Dependencies/Members/MethodCallDependencyTests.cs
ArchUnitNETTests/Domain/Dependencies/Members/MethodDependencyTestBuild.cs

Issue: #138
Resolves #138
Signed-off-by: Wolf-Dieter Hofmann <hofmann9999@gmx.de>

Scan nested async helper class

---

ArchUnitNET/Domain/Extensions/TypeExtensions.cs
ArchUnitNET/Domain/MethodMember.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MethodMembers/MethodMemberConditionsDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MethodMembers/MethodMemberPredicatesDefinition.cs
ArchUnitNETTests/Fluent/Syntax/Elements/MatchGenericReturnTypesTests.cs

Match generic return types correctly with HaveReturnType(typeof(...))

---

renovate.json

Signed-off-by: gatherf <florian.gather@tngtech.com>

Ignore test libraries in renovate

---

ArchUnitNET/Fluent/Syntax/Elements/Members/MemberConditionsDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MemberPredicatesDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MethodMembers/MethodMemberConditionsDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MethodMembers/MethodMemberPredicatesDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/ObjectConditionsDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/ObjectPredicatesDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Types/TypeConditionsDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Types/TypePredicatesDefinition.cs
ArchUnitNETTests/Fluent/NoErrorReferencingOfTypesOutsideOfArchitectureTests.cs
TestAssembly/EmptyTestClass.cs

Fix typeof(...) referencing to types which are not in the architecture caused the rule to always fail

---

ArchUnitNET/Domain/PlantUml/Export/DependencyFilters.cs
ArchUnitNET/Domain/PlantUml/Export/GenerationOptions.cs
ArchUnitNET/Domain/PlantUml/Export/PlantUmlClass.cs
ArchUnitNET/Domain/PlantUml/Export/PlantUmlDependency.cs
ArchUnitNET/Domain/PlantUml/Export/PlantUmlFileBuilder.cs
ArchUnitNET/Domain/PlantUml/Export/PlantUmlInterface.cs
ArchUnitNET/Domain/PlantUml/Export/RenderOptions.cs
ArchUnitNET/Fluent/PlantUml/PlantUmlFluentComponentDiagramInitializer.cs
ArchUnitNETTests/Domain/PlantUml/PlantUmlFileBuilderTest.cs
ArchUnitNETTests/Fluent/PlantUml/PlantUmlFluentComponentDiagramTests.cs

Add GenerationOptions to have more control over PlantUML diagram generation to only show dependencies of interest.

More plantuml generation features

---

ArchUnitNET/Fluent/ConditionManager.cs

Hello again :smiley: 
Previously I was writing tests that check relations between assemblies and classes in our solution. Afterwards I've decided to try and check the number of usages of a deprecated implementation of Service Locator in our codebase. And this test ran very slow, so I've opened the profilier once again and spotted the bottleneck. This quadratic behavior was more or less okay when I was analyzing relations between classes, but when I started to analyze members it took off, because there are 130000 members in our solution. 
For the number of elements in the condition i did a simple micro-benchmark check and somewhere between 128 and 256 elements the dict lookup becomes 2-3x faster than search in the list - hence the number.

Added dictionary as a ordering/search method for large enough evaluation results

---

documentation/docs/guide.md

Add language hint for proper syntax highlighting and improve readability a tiny bit.

Increase readability of code samples in guide

---

ArchUnitNET/Domain/FieldMember.cs
ArchUnitNET/Domain/IMember.cs
ArchUnitNET/Domain/MethodMember.cs
ArchUnitNET/Domain/PropertyMember.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/GivenMembersThat.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MemberConditionsDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MemberPredicatesDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/MembersShould.cs
ArchUnitNET/Fluent/Syntax/Elements/Members/ShouldRelateToMembersThat.cs
ArchUnitNET/Loader/LoadTasks/AddMembers.cs
ArchUnitNET/Loader/TypeFactory.cs
ArchUnitNETTests/ArchUnitNETTests.csproj
ArchUnitNETTests/Domain/MemberTests.cs
ArchUnitNETTests/Fluent/Extensions/BuildMocksExtensions.cs
global.json

Signed-off-by: Andrii Derevianko <andredered@gmail.com>

Checking for immutability solution v2

---

documentation/docs/guide.md

Fixes the - probably outdated - names of the nuget packages.
Adds hint for MSTest v2 package.

Fix nuget package name

---

ArchUnitNET/Domain/Extensions/TypeExtensions.cs
ArchUnitNET/Fluent/Syntax/Elements/Types/GivenTypesThat.cs
ArchUnitNET/Fluent/Syntax/Elements/Types/ShouldRelateToTypesThat.cs
ArchUnitNET/Fluent/Syntax/Elements/Types/TypeConditionsDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Types/TypePredicatesDefinition.cs
ArchUnitNET/Fluent/Syntax/Elements/Types/TypesShould.cs
ArchUnitNETTests/Domain/StaticTestTypes.cs
ArchUnitNETTests/Fluent/Syntax/Elements/TypeSyntaxElementsTests.cs
ExampleTest/ExampleArchUnitTest.cs

Added solution for https://github.com/TNG/ArchUnitNET/issues/179#issue-1378631024

Nested types for a given type

---

.travis.yml
ArchUnitNET.MSTestV2Tests/ArchUnitNET.MSTestV2Tests.csproj
ArchUnitNET.NUnitTests/ArchUnitNET.NUnitTests.csproj
ArchUnitNETTests/ArchUnitNETTests.csproj
ExampleTest/ExampleTest.csproj
Travis/test_linux.sh
global.json

Signed-off-by: Andrii Derevianko <andredered@gmail.com>

To v6 update fix travis errors

---

ArchUnitNET/Domain/Assembly.cs
ArchUnitNET/Loader/ArchBuilder.cs
ArchUnitNET/Loader/ArchLoader.cs
ArchUnitNET/Loader/AssemblyRegistry.cs
ArchUnitNET/Loader/TypeFactory.cs
ArchUnitNETTests/Fluent/ArchRuleEqualityTests.cs
ArchUnitNETTests/Fluent/Extensions/BuildMocksExtensions.cs

Resolved https://github.com/TNG/ArchUnitNET/issues/129

Assemblies show list of names for referenced Assemblies
